### ISSUE TITLE
Error when registering the latest version - No overload matches this call.

### ISSUE THREAD

**Issue by BE-CH** [Eomm/fastify-raw-body#43]
I get the error below when trying to register the plugin.

![image](https://user-images.githubusercontent.com/1050050/205675856-487b7f21-6c93-48e7-b785-5a543bdd3483.png)

```
instance.d.ts(115, 19): This type parameter might need an `extends T extends (...args: any[]) => any ? (this: FastifyRequest<RouteGenericInterface, RawServerDefault, http.IncomingMessage, ... 4 more ..., ResolveFastifyRequestType<...>>, ...args: Parameters<T>) => ReturnType<...> : T` constraint.
```

**My code:**
```ts
import fastifyRawBody from 'fastify-raw-body';

// Register FastifyRAW
await fastify.register(fastifyRawBody, {
  field: 'rawBody', // change the default request.rawBody property name
  global: false, // add the rawBody to every request. **Default true**
  encoding: 'utf8', // set it to false to set rawBody as a Buffer **Default utf8**
  runFirst: true, // get the body before any preParsing hook change/uncompress it. **Default false**
  routes: ['/order/webhook'], // array of routes, **`global`** will be ignored, wildcard routes not supported
});
```

**My packages:**
```
    "fastify": "^4.10.2",
    "fastify-raw-body": "^4.1.3",
```

Not sure why it happens - but it happened after I updated to the latest version. It also happened with some other plugins, but I just updated those and the error when away for the other plugins

**Comment by Eomm** [comment]
I think we should apply the same `nodenext` TS compatibility here
https://github.com/search?q=org%3Afastify+nodenext&type=pullrequests

Could you try to install fastify `v4.10.0`?
Which was your previous version in use?

**Comment by BE-CH** [comment]
> I think we should apply the same `nodenext` TS compatibility here https://github.com/search?q=org%3Afastify+nodenext&type=pullrequests
> 
> Could you try to install fastify `v4.10.0`? Which was your previous version in use?

It does not seem to make any difference in ``Fastify v4.10.0``. 

I previously used these versions:
```
    "fastify": "^4.9.2",
    "fastify-raw-body": "^4.1.3",
```

but that seems to not even work🤔
```
FastifyError [Error]: fastify-plugin: fastify-raw-body - expected '^4.10.x' fastify version, '4.9.2' is installed```

**Comment by Eomm** [comment]
> FastifyError [Error]: fastify-plugin: fastify-raw-body - expected '^4.10.x' fastify version, '4.9.2' is installed

Yes, this was necessary because now this plugin uses `request.routeOptions` that was released in fastify v4.10

> I got it working with the versions below:

Thanks, it is helpful to replicate and solve the issue

**Comment by Eomm** [comment]
@BE-CH could you verify that the PR #45 works for you?

**Comment by BE-CH** [comment]
> @BE-CH could you verify that the PR #45 works for you?

It works! Thank you so much :)

**Comment by Eomm** [comment]
I did not release it

I will close later today

**Comment by BE-CH** [comment]
@Eomm will you release it to a new version? or can I simply just do ``yarn install`` again to get the latest additions?

**Comment by Eomm** [comment]
4.2.0 released now!
