### ISSUE TITLE
Missing parameters in secureJson.parse

### ISSUE THREAD

**Issue by theolpmodesto** [Eomm/fastify-raw-body#51]
I noticed that the function secureJson.parse has 3 parameters, but it only utilizes 2. After updating from Fastify 3v to v4, I encountered some errors.
<img width="978" alt="Screenshot 2023-08-01 at 21 31 12" src="https://github.com/Eomm/fastify-raw-body/assets/108004154/27ae33e5-c409-4be7-95f9-5c0664366811">
<img width="1112" alt="Screenshot 2023-08-01 at 21 29 00" src="https://github.com/Eomm/fastify-raw-body/assets/108004154/bcd76126-95de-449c-96dc-f1dba47e09f5">

**Comment by Eomm** [comment]
It has 2 optional args and the first one that is mandatory:
https://github.com/fastify/secure-json-parse#sjsonparsetext-reviver-options


Here is the method overload:

https://github.com/fastify/secure-json-parse/blob/master/types/index.d.ts#L56

Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.
