### ISSUE TITLE
Not working with common js

### ISSUE THREAD

**Issue by ayami123** [Eomm/fastify-raw-body#62]
The Entire Plugin didn't add anything when using commonJS

**Comment by Eomm** [comment]
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

**Comment by ayami123** [comment]
it's okay, I already move from fastify back to express :)
I'll close the ticket

**Comment by Eomm** [comment]
Please, take a moment to read ["Why you should not say _«I will use X»_ to a Fastify maintainer"](https://gist.github.com/Eomm/4b72531ed9e2bdaefccf144ff9d7ce9a).

Thank you
